name: Rocket Launch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  launch:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
      
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: cd /home/dotco/github/ && python3 rocket_countdown.py